### ISSUE TITLE
Updates tracker

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/bench-wizard#1]
- [x] Create storage heavy benchmark (can be inspired by actual substrate benchmark)
- [x] Dump bench details after failed benchmark
- [x] Rerun once if some failed and some ok
- [ ] Automatic weight update on benchbot run
- [ ] Show something that resembles progress since it's running very long now (maybe we can split build and test phases?)
- [x] Add percentage results
- [ ] Increase verbosity
- [ ] Show system info

HydraDX-node [issue](https://github.com/galacticcouncil/HydraDX-node/issues/119)

**Comment by jak-pan** [comment]
I'd add one more - get public IP / submit this benchmark to our db / endpoint. So that we can automate validator incentivization.
